### ISSUE TITLE
SyntaxError: Function statements require a function name

### ISSUE THREAD

**Issue by Flynsarmy** [Wilkolicious/twitchAdSkip#10]
Followed the steps to install the user script but upon refreshing the browser I get:

> VM160:62 Syntax error @ "twitchAdSkip"!
> ##########################
> JSHINT output:
> ##########################
> 
> SyntaxError: Function statements require a function name
>     at eval (<anonymous>)
>     at <anonymous>:3:100
>     at Object.N [as F_c] (<anonymous>:2:148)
>     at Object.E_u (<anonymous>:3:274)
>     at Ka (eval at exec_fn (:1:157), <anonymous>:61:375)
>     at Object.create (eval at exec_fn (:1:157), <anonymous>:73:235)
>     at L (eval at exec_fn (:1:157), <anonymous>:12:208)

Tampermonkey shows the same thing in the editor
![image](https://user-images.githubusercontent.com/334808/98457403-9f09cb00-21d2-11eb-863e-b078a795f9a9.png)

**Comment by Flynsarmy** [comment]
Fixed this by copying the code from [here](https://github.com/Wilkolicious/twitchAdSkip/blob/main/twitchAdSkip.js). The gists listed in the *updateURL* and *downloadURL* (and the URL you're told to use in the installation instructions) have the old, broken code.

**Comment by Wilkolicious** [comment]
> Fixed this by copying the code from [here](https://github.com/Wilkolicious/twitchAdSkip/blob/main/twitchAdSkip.js). The gists listed in the _updateURL_ and _downloadURL_ (and the URL you're told to use in the installation instructions) have the old, broken code.

If you click your link then press the “raw” button, you’ll get to the exact same url listed as the ‘updateURL’ & ‘downloadURL’ + installation instructions - it’s the same code. I’ve just looked and there’s no line break there that is causing the error you have

I suspect what _actually_ caused the error is that you pasted it fine but then accidentally modified it by pressing the enter button on your keyboard. 

This is user error - happy to reopen if you can show me the steps to reproduce this and prove otherwise. Cheers

**Comment by Flynsarmy** [comment]
This is not user error, it's a problem with your installation instructions and your gist.

The installation instructions state:
> Copy the [script](https://raw.githubusercontent.com/Wilkolicious/twitchAdSkip/main/twitchAdSkip.js) to your clipboard
Open that file and look at line 62. You'll see the following function with no name:
```javascript
function(videoPlayerEl) {
```
Now look at line 62 of the source code in your repo:
https://github.com/Wilkolicious/twitchAdSkip/blob/main/twitchAdSkip.js

Notice how it's completely different? The above unnamed function doesn't even appear in that code.

**Comment by Flynsarmy** [comment]
Figured it out. Was an issue with the [PrettyPrint chrome extension](https://chrome.google.com/webstore/detail/prettyprint/nipdlgebaanapcphbcidpmmmkcecpkhg) messing with the JS file before displaying it. Guess that ones getting an uninstall!

**Comment by Wilkolicious** [comment]
Glad you figured it out @Flynsarmy!
